export const appTitleBase: string;
export const fontawesomeglyphs: string;
export const image: string;
export const errorMessage: string;
export const editor: string;
export const edit: string;
export const counterOverLimit: string;
export const fadein: string;
export const fadeout: string;
